### ISSUE TITLE
Stateful loops in Text.Gigaparsec.State are not stateful.

### ISSUE THREAD

**Issue by david-davies** [j-mie6/gigaparsec#40]
The loops in [Text.Gigaparsec.State](https://github.com/j-mie6/gigaparsec/blob/39b1ce35ab92176f2ffff20548c45b63198fdf8d/src/Text/Gigaparsec/State.hs) don't use `Ref`s.

For example, the definition of `forP'`,
https://github.com/j-mie6/gigaparsec/blob/39b1ce35ab92176f2ffff20548c45b63198fdf8d/src/Text/Gigaparsec/State.hs#L79-L85

Am I mistaken?

**Comment by j-mie6** [comment]
No mistake here!

For gigaparsec it is less important that these combinators internally use references, as we do have access to an _efficient_ `>>=`, unlike the parsleys. This combinator is still most useful for stateful work involving other variables.

The extrinsic behaviours of the combinator remain the same, even when the intrinsic implementation is different.

**Comment by david-davies** [comment]
Should these be moved out of `Text.Gigaparsec.State` then? Or would that break API parity with `scala-parsley`?
And from your answer I think you mean their implementation need not change, it is already similar speed to using refs?
