### ISSUE TITLE
Override default docs for `some` and `many`

### ISSUE THREAD

**Issue by david-davies** [j-mie6/gigaparsec#41]
[Text.Gigaparsec](https://github.com/j-mie6/gigaparsec/blob/39b1ce35ab92176f2ffff20548c45b63198fdf8d/src/Text/Gigaparsec.hs) re-exports `some` and `many` from `Control.Applicative`, whose documentation for these combinators is crap.

We could either:

- Define local versions that just inline to the applicative versions: `many = Control.Applicative.many {-# inline many #-}`, and attach better documentation to these. I don't know if there may be downsides to this. Plus, it seems bad to change the implementation for the sake of documentation, although I know user-friendliness is a specific goal of `gigaparsec`.
- Figure out a way to override the documentation of re-exports in haddock.

**Comment by j-mie6** [comment]
Yes, it's frankly infuriatingly bad. See also `(<|>)`.

The original parsec did expose it's own versions of these combinators, allowing for good docs. The downside is that these are treated as specific by GHC, and if you want to use the more generic operations, you'll need to explicitly hide gigaparsecs.

Long term, the right solution would probably be a GHC proposal to allow for haddock to be overwritten by instances, and re-exported. In turn the docs would be picked up for the library, and if the type is monomorphic enough, even when used in the IDE (this is how Scaladoc works, for instance). Perhaps I should have made that a Master's project for this year to implement...
